name: release

on:
  workflow_dispatch:

env:
  version: 122
  dotversion: 1.22
  SRC: fshtool.c
  DEST: fshtool
  BRANCHES: -DUVTVUTF8

jobs:
  win32:
    runs-on: ubuntu-latest

    name: Compile (Windows x86)
    steps:
      - uses: actions/checkout@v3

      - name: Install compiler
        run: |
          sudo apt install gcc-mingw-w64-i686

      - name: Build
        run: |
          MINGWFLAGS='-std=c89 -fPIE -O0 -Xlinker --no-insert-timestamp'
          # MINGWFLAGS='-std=c89 -fPIE -fstack-clash-protection -s -O2 -Xlinker --no-insert-timestamp'

          echo "mingw-win32"
          i686-w64-mingw32-gcc-win32 $MINGWFLAGS "${{ env.SRC }}" -o "${{ env.DEST }}.exe" ${{ env.BRANCHES }}

          sha256sum "${{ env.DEST }}.exe"
          md5sum "${{ env.DEST }}.exe"

      - name: Create archive
        run: |
          7z a -tzip "${{ env.DEST }}_noprompt.zip" \
          readme.txt \
          ${{ env.DEST }}.exe \
          fshtool.c

      - name: Store archive
        uses: actions/upload-artifact@v3
        with:
          name: "${{ env.DEST }}_noprompt.zip"
          path: "${{ env.DEST }}_noprompt.zip"
          retention-days: 7
